# np.append() :

**Purpose**:<br>
Adds values to the end of an array, returns a new array.

**Syntax**:<br>
np.append(arr, values, axis=None)

In [7]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
np.append(a, [5, 6])
# Output: array([1, 2, 3, 4, 5, 6])

array([1, 2, 3, 4, 5, 6])

In [8]:
a

array([[1, 2],
       [3, 4]])

In [9]:
np.append(a,[[5,6]],axis=0) #row wise appending

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
np.append(a,[[5],[6]],axis=1) #column wise appending

array([[1, 2, 5],
       [3, 4, 6]])

## NOTE:<br>
- Parameters:
  - arr: Input array.

  - values: Values to append.

  - axis (optional):

  - None (default) → flattens both arrays and appends.

  - 0 or 1 → appends along rows or columns (requires matching shape).

- Shapes must match when axis is specified.