# np.concatenate()

- Purpose:
Combines two or more arrays along an existing axis.

- Syntax:
np.concatenate((a1, a2, ...), axis=0)

- Parameters:
  - (a1, a2, ...): Tuple or list of arrays to join.

  - axis: Axis along which arrays are joined (default = 0).

In [1]:
import numpy as np

#Concatenate 1D arrays:
a=np.array([1,2])
b= np.array([3,4])
np.concatenate((a,b))
# Output: [1 2 3 4]

array([1, 2, 3, 4])

In [ ]:
#concatenating 2D array along rows(axis=0)
a = np.array([[1, 2]])
b = np.array([[3, 4]])
np.concatenate((a, b), axis=0)
# Output: [[1 2], [3 4]]

array([[1, 2],
       [3, 4]])

In [ ]:
#concatenating 2D arrays along columns(axis=1)
a = np.array([[1], [2]])
b = np.array([[3], [4]])
np.concatenate((a, b), axis=1)
# Output: [[1 3], [2 4]]

array([[1, 3],
       [2, 4]])