# Set Functions:

In [2]:
import numpy as np
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

## np.union1d()

In [3]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

---

## np.intersect1d():

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

---

## np.setdiff1d():

In [7]:
np.setdiff1d(m,n)

array([1, 2])

In [8]:
np.setdiff1d(n,m)

array([6, 7])

---

## np.setxor1d():
- Delete duplicates and returns only unique elements from the combined arrays

In [10]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

---

## np.in1d():
- Similar to membership operator

In [13]:
np.in1d(m,1)

C:\Users\anike\AppData\Local\Temp\ipykernel_3796\3930963099.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])