# np.unique()

- Returns unique values from an array given as parameter in np.unique()

In [8]:
import numpy as np
a=np.array([1,2,1,1,2,3,3,3,4,5,5,6,6,8])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 8])

---

# np.expand_dims()
It is used to expand the dimensions of an array i.e. convert  a 1D array to a 2d array or a 2d array to a 3D array.

In [9]:
np.expand_dims(a,axis=0).shape

(1, 14)

In [10]:
np.expand_dims(a,axis=1).shape

(14, 1)

---

# np.where()
- Purpose:
Returns Indices **or** elements based on a condition

- Syntax: 
np.where(condition, x,y)

- Parameters:
  - condition: Boolean condition.

  - x, y (optional): Values to choose from.

    - If provided → returns elements from x where condition is True, else from y.

- Returns:
  - If only condition is given → **tuple**
   of indices.

  - If x and y are given → **array** with selected values.

In [12]:
# Get indices where contion is true
a= np.array([10,20,30,40])
np.where(a>25)

(array([2, 3]),)

In [13]:
# Replace values conditionally
np.where(a> 25,1,0)

array([0, 0, 1, 1])

---

# np.argmax() and np.argmin():
- Returns **indices** of maximum and minimum element of the array respectfully in a particular axis.

In [14]:
np.argmax(a)

np.int64(3)

In [15]:
np.argmin(a)

np.int64(0)

In [29]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.argmax(a,axis=0)

array([2, 2, 2])

In [31]:
np.argmin(a,axis=1)

array([0, 0, 0])

---

# np.cumsum():
Used to compute the cumulative sum of an array elements over a given axis.

In [34]:
a=np.random.randint(1,100,size=(1,50))
a

array([[69, 23, 91, 74, 78, 45, 87,  5, 20, 69, 56, 42, 19,  2, 47,  9,
        55, 16, 92, 84, 59, 94, 34, 12, 71,  1, 71, 32, 21, 95, 77, 29,
         7, 66, 94, 27, 21, 24, 64,  6, 24, 34, 60, 92, 17, 36, 20, 65,
         8,  6]], dtype=int32)

In [35]:
np.cumsum(a)

array([  69,   92,  183,  257,  335,  380,  467,  472,  492,  561,  617,
        659,  678,  680,  727,  736,  791,  807,  899,  983, 1042, 1136,
       1170, 1182, 1253, 1254, 1325, 1357, 1378, 1473, 1550, 1579, 1586,
       1652, 1746, 1773, 1794, 1818, 1882, 1888, 1912, 1946, 2006, 2098,
       2115, 2151, 2171, 2236, 2244, 2250])

In [40]:
a=np.random.randint(1,100,size=(4,5))
a

array([[35, 78, 81, 19, 74],
       [48, 48, 47,  3, 72],
       [95, 84, 62, 66, 14],
       [67, 84, 21, 64, 59]], dtype=int32)

In [44]:
np.cumsum(a,axis=1)

array([[ 35, 113, 194, 213, 287],
       [ 48,  96, 143, 146, 218],
       [ 95, 179, 241, 307, 321],
       [ 67, 151, 172, 236, 295]])

---

# np.cumprod():
Used to find the cumulative product of an array along a given axis

In [45]:
np.cumprod(a,axis=0)

array([[      35,       78,       81,       19,       74],
       [    1680,     3744,     3807,       57,     5328],
       [  159600,   314496,   236034,     3762,    74592],
       [10693200, 26417664,  4956714,   240768,  4400928]])

In [46]:
np.cumprod(a,axis=1)

array([[       35,      2730,    221130,   4201470, 310908780],
       [       48,      2304,    108288,    324864,  23390208],
       [       95,      7980,    494760,  32654160, 457158240],
       [       67,      5628,    118188,   7564032, 446277888]])

---

# np.percentile():
Used to find the element of a given percentile along a given axis

In [51]:
a

array([[35, 78, 81, 19, 74],
       [48, 48, 47,  3, 72],
       [95, 84, 62, 66, 14],
       [67, 84, 21, 64, 59]], dtype=int32)

In [ ]:
np.percentile(a,50) 

np.float64(63.0)

In [56]:
np.median(a) #returns the median = 50 percentile

np.float64(63.0)

In [53]:
np.percentile(a,0,axis=0)

array([35., 48., 21.,  3., 14.])

---

# np.histogram():
Computes the frequency distribution of data (like making a histogram).

- Syntax:
np.histogram(data, bins=10, range=None)

- Parameters: 
  - bin: equal parts in which array is divided
  - range: to divide only a range of array in given no. of bins rather than whole array

In [71]:
a=np.random.randint(0,100,size=(1,25))
a

array([[46, 73, 69, 61, 69, 97, 66, 92,  2, 58, 46,  7, 93, 80, 16, 11,
        80, 66, 17,  6, 27,  4, 52, 71, 68]], dtype=int32)

In [75]:
np.histogram(a,bins=3,range=(20,80))

(array([ 1,  4, 10]), array([20., 40., 60., 80.]))

---

# np.corrcoef():
Used to find the correralation coefficient of two given datas.

- Syntax:
np.corrcoef(x, y=None)

- Parameters:
  - x: Input array (1D or 2D)

  - y: Optional second array (if not passed, only x is used)

- Returns:
  - A correlation matrix, where:

  - Value 1.0 means perfect positive correlation

  - Value -1.0 means perfect negative correlation

  - Value 0.0 means no correlation

In [78]:
salary = [10000,20000,30000,40000]
exp = [2,2,3,6]
np.corrcoef(salary,exp)

array([[1.        , 0.88659264],
       [0.88659264, 1.        ]])

---

# np.isin():
Use to membership of multiple items in an array which are passed using a list.

- Syntax: np.isin(a,items) #items is a list

In [84]:
items=[73,92,69,48,51]
a

array([[46, 73, 69, 61, 69, 97, 66, 92,  2, 58, 46,  7, 93, 80, 16, 11,
        80, 66, 17,  6, 27,  4, 52, 71, 68]], dtype=int32)

In [86]:
np.isin(a,items)

array([[False,  True,  True, False,  True, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False]])

---

# np.flip()
Reverses the order of array function along the specified axis, preserving the shape of the array.

In [87]:
a

array([[46, 73, 69, 61, 69, 97, 66, 92,  2, 58, 46,  7, 93, 80, 16, 11,
        80, 66, 17,  6, 27,  4, 52, 71, 68]], dtype=int32)

In [89]:
np.flip(a)

array([[68, 71, 52,  4, 27,  6, 17, 66, 80, 11, 16, 80, 93,  7, 46, 58,
         2, 92, 66, 97, 69, 61, 69, 73, 46]], dtype=int32)

In [90]:
b=np.random.randint(1,100,size=(4,5))
b

array([[95, 85, 59, 58, 35],
       [71, 40, 90, 52, 86],
       [66, 11, 85, 68, 75],
       [53, 52,  2, 15, 64]], dtype=int32)

In [91]:
np.flip(b, axis=0) #column wise flipping

array([[53, 52,  2, 15, 64],
       [66, 11, 85, 68, 75],
       [71, 40, 90, 52, 86],
       [95, 85, 59, 58, 35]], dtype=int32)

In [ ]:
np.flip(b,axis=1) #row wise flipping\

array([[35, 58, 59, 85, 95],
       [86, 52, 90, 40, 71],
       [75, 68, 85, 11, 66],
       [64, 15,  2, 52, 53]], dtype=int32)

---

# np.put()
Replaces specific elements of the array with given values at the specific indices. Indices work on flattened array.

In [93]:
a

array([[46, 73, 69, 61, 69, 97, 66, 92,  2, 58, 46,  7, 93, 80, 16, 11,
        80, 66, 17,  6, 27,  4, 52, 71, 68]], dtype=int32)

In [98]:
np.put(a,[0,1],[460,730]) #this will make change into he original array
a

array([[460, 730,  69,  61,  69,  97,  66,  92,   2,  58,  46,   7,  93,
         80,  16,  11,  80,  66,  17,   6,  27,   4,  52,  71,  68]],
      dtype=int32)

---

# np.delete():
Returns a new array with the deletion of sub-arrays along with the mentioned axis.

In [99]:
a

array([[460, 730,  69,  61,  69,  97,  66,  92,   2,  58,  46,   7,  93,
         80,  16,  11,  80,  66,  17,   6,  27,   4,  52,  71,  68]],
      dtype=int32)

In [102]:
np.delete(a,[0,3,7])

array([730,  69,  69,  97,  66,   2,  58,  46,   7,  93,  80,  16,  11,
        80,  66,  17,   6,  27,   4,  52,  71,  68], dtype=int32)

---